include:
  - project: 'internal/integration/ci/pipelines/container'
    ref: main
    file: 'pipeline.yml'

variables:
  #TRIVY_IGNORE_UNFIXED: "true"
  TRIVY_IGNOREFILE: ".trivyignore"
  CHECKOV_SKIP_CHECK: 
  CONTAINER_REGISTRY: "${CI_REGISTRY}/registry/public"
  CONTAINER_REGISTRY_USER: ${CI_REGISTRY_USER}
  CONTAINER_REGISTRY_PASSWORD: ${DEVELOPER_REGISTRY_WRITE_TOKEN}

publish-container:
  variables:
    CONTAINER_REGISTRY_PASSWORD: ${DEVELOPER_REGISTRY_WRITE_TOKEN}
    DESTINATIONS: "${CONTAINER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} ${CONTAINER_REGISTRY}/${CI_PROJECT_NAME}:latest"

